In [2]:
import numpy as np

def is_diagonally_dominant(matrix):
    matrix = np.array(matrix)
    n = matrix.shape[0]
    for i in range(n):
        diagonal_element = abs(matrix[i][i])
        row_sum = np.sum(np.abs(matrix[i])) - diagonal_element
        if diagonal_element < row_sum:
            return False
    return True
matrix_a = [[4, 1, 1],
            [2, 5, 1],
            [0, 1, 3]]
matrix_b = [[1, 2, 3],
            [4, 5, 6],
            [7, 8, 9]]

def run_challenge(matrix):
    print(np.array(matrix))
    result = is_diagonally_dominant(matrix)
    print("Is the matrix diagonally dominant? {}".format(result))

run_challenge(matrix_a)
run_challenge(matrix_b)

[[4 1 1]
 [2 5 1]
 [0 1 3]]
Is the matrix diagonally dominant? True
[[1 2 3]
 [4 5 6]
 [7 8 9]]
Is the matrix diagonally dominant? False
